# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/yjagdale/siem-data-producer
  DOCKER_DRIVER: overlay

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build
  - package

format:
  stage: test
  script:
    - go mod download
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  needs: [ "format" ]
  script:
    - go mod download
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/siem-data-producer
  artifacts:
    paths:
      - $CI_PROJECT_DIR/siem-data-producer

docker-build:
  image: docker:latest
  needs: [ "compile", "format" ]
  services:
    - docker:dind
  stage: package
  script:
    - docker build -t registry.gitlab.com/yjagdale/siem-data-producer:$CI_COMMIT_SHORT_SHA -tregistry.gitlab.com/yjagdale/siem-data-producer .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/yjagdale/siem-data-producer
    - docker push registry.gitlab.com/yjagdale/siem-data-producer:$CI_COMMIT_SHORT_SHA
