image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/Team-R1A3/frontend-aws
  DOCKER_REPO_NAME: registry.gitlab.com/team-r1a3/frontend-aws
  CI_REGISTRY: registry.gitlab.com
  DOCKER_DRIVER: overlay

stages:
  - test
  - build
  - package

format:
  stage: test
  image: node
  script:
    - echo "Start building App"
    - npm install
    - npm build
    - echo "Test successfully!"

compile:
  stage: build
  needs: [ "format" ]
  script:
    - echo "Start building App"
    - npm install
    - npm build
    - echo "Build successfully!"
  cache: &global_cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - public/
      - vendor/
    policy: pull-push
  artifacts:
    expire_in: 1 hour
    paths:
      - build

docker-build:
  image: docker:latest
  needs: [ "compile", "format" ]
  services:
    - docker:dind
  stage: package
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

  script:
    - docker build -t "$DOCKER_REPO_NAME:$CI_COMMIT_SHORT_SHA" -t "$DOCKER_REPO_NAME" .
    - docker build --pull -t "$DOCKER_REPO_NAME:$CI_COMMIT_SHORT_SHA" .
    - docker push "$DOCKER_REPO_NAME:$CI_COMMIT_SHORT_SHA"
    - echo "Registry image:" $DOCKER_REPO_NAME
